Migrating the rules from Aqua commercial/Kube Enforcer into defsec
aquasecurity/defsec pull request #1049
Opened 2022-11-10 13:06 UTC by dheerajkadri

Few rules which are present in Aqua product (which is used by Kube-enforcer) is not present in defsec. Migrating few policies to aquacommercial folder

2022-11-10 13:47 UTC, dheerajkadri commented on internal/rules/policies/kubernetes/policies/aquacommercial/configMap_with_sensitive_test.rego
> +test_configMap_with_sensitive_denied {
Example for CM with sensitive data . Sensitive data is present in keys (**ex:email.id**) and also in key part of value (**username**=myusername)
![image](https://user-images.githubusercontent.com/50172913/201108319-2a32db3a-e579-4ede-92a2-27512f5588d0.png)

2022-11-10 13:49 UTC, dheerajkadri commented on internal/rules/policies/kubernetes/policies/aquacommercial/service_with_externalip_test.rego
> +	r := deny with input as {
Example for service with external ip
![image](https://user-images.githubusercontent.com/50172913/201108786-69398e27-1d6b-492d-a85c-c55c832c71e9.png)

2022-11-10 14:03 UTC, owenrumney requested changes
Some small points, but otherwise looks good

2022-11-10 14:03 UTC, owenrumney commented on internal/rules/policies/kubernetes/policies/aquacommercial/service_with_externalip.rego
> +	msg := sprintf("%s %s in %s namespace should not set external IPs or external Name", [lower(kubernetes.kind), kubernetes.name, kubernetes.namespace])
Think this should be wrapped in a `kubernetes.format` like https://github.com/aquasecurity/defsec/blob/master/internal/rules/policies/kubernetes/policies/general/memory_not_limited.rego#L40

2022-11-10 14:46 UTC, owenrumney approved these changes
LGTM

2022-11-11 08:51 UTC, owenrumney approved these changes
Nice! LGTM :rocket:

2022-11-11 14:05 UTC, merged

2022-11-24 23:05 UTC, simar7 commented
hi @dheerajkadri - just wondering how did you add the impact to the AVD markdown files when making this change? Was it manually added or the `make docs` makefile directive generate the markdowns for you?