fix: bucket encryption is enabled if SSEAlgorithm is specified
aquasecurity/defsec pull request #1068
Opened 2022-11-18 23:00 UTC by int-tt

Resolves: https://github.com/aquasecurity/defsec/issues/1067

2022-11-23 05:54 UTC, simar7 requested changes
thanks looks good, I left some feedback in the comments.

2022-11-23 05:54 UTC, simar7 commented on internal/adapters/cloud/aws/s3/s3_test.go
> -					BucketKeyEnabled: true,
I would keep this in, as it is another way for a bucket to be encrypted. As for the test, if you implement the suggestion I mentioned above, the test should be green for the cases when either `BucketKeyEnabled` and / or `ApplyServerSideEncryptionByDefault` is set.

Ideally they should be two different cases but I think we can leave that for now if you wish.

2022-11-24 17:40 UTC, int-tt commented
Thank you for feedback!
I fixed it.

2022-11-25 00:04 UTC, simar7 commented
> Thank you for feedback!
> I fixed it.

Looks like there's a few checks that are red, could you address those?

2022-11-25 23:05 UTC, simar7 approved these changes
thanks!

2022-11-25 23:05 UTC, merged