feat(cloud): add availability zone filed for rds cluster
aquasecurity/defsec pull request #1424
Opened 2023-08-12 11:45 UTC by int-tt

There is a behavior in `availability_zones` in `aws_rds_cluster` that may cause resource re-creation to be performed. An additional parameter has been added to allow inspection of this issue.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#availability_zones

2023-08-15 07:38 UTC, knqyf263 commented
🤠

2023-08-17 05:56 UTC, simar7 requested changes
Left a couple of comments.

2023-08-17 05:56 UTC, simar7 commented on internal/adapters/cloudformation/aws/rds/cluster.go
> +			AvailabilityZones:    nil,
omit
```suggestion
```

2023-08-17 05:56 UTC, simar7 commented on internal/adapters/terraform/aws/rds/adapt.go
> +			AvailabilityZones:    nil,
```suggestion
```

2023-08-18 06:16 UTC, simar7 approved these changes

2023-08-18 06:35 UTC, merged