feat(cloud): add the DeletionProtection attribute to the RDS Cluster
aquasecurity/defsec pull request #1443
Opened 2023-08-31 14:45 UTC by dorayakikun

## motivation

I want to avert some human mistakes in the RDS Cluster, but I can't detect them now.
( Now, I can only detect the RDS instance's deletionProtection. )

For example, the below codes are not working as intended.

```
deny[res] {
	cluster := input.aws.rds.clusters[_]
        instance := cluster.instances[_]
	not instance.deletionprotection.value
	res := result.new("Cluster does not have Deletion Protection enabled", instance.deletionprotection)
}
```

So, I would like to add the DeletionProtection attribute to the RDS Cluster.

2023-08-31 14:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/defsec?pullRequest=1443) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/defsec?pullRequest=1443) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/defsec?pullRequest=1443) it.</sub>

2023-08-31 22:31 UTC, simar7 commented
> ## motivation
> I want to avert some human mistakes in the RDS Cluster, but I can't detect them now. ( Now, I can only detect the RDS instance's deletionProtection. )
> 
> For example, the below codes are not working as intended.
> 
> ```
> deny[res] {
> 	cluster := input.aws.rds.clusters[_]
>         instance := cluster.instances[_]
> 	not instance.deletionprotection.value
> 	res := result.new("Cluster does not have Deletion Protection enabled", instance.deletionprotection)
> }
> ```
> 
> So, I would like to add the DeletionProtection attribute to the RDS Cluster.

I see. Thanks for the PR. Would you also mind creating a new Rego Rule for the clusters too? It would be similar to this rule we have for instances: https://github.com/aquasecurity/defsec/blob/master/rules/cloud/policies/aws/rds/enable_deletion_protection.rego - I think it could be beneficial for other users too.

2023-08-31 22:31 UTC, simar7 requested changes
left a comment and you would also need to run `make schema` and commit the changes to pass the tests.

2023-09-01 12:58 UTC, dorayakikun commented
I appreciate your warm dealing.
I've tried to add docs and policies.

Are these processes correct?
If there are any problems, please let me know.

2023-09-01 22:29 UTC, simar7 commented on rules/cloud/policies/aws/rds/enable_cluster_deletion_protection.rego
> +# description: "Ensure deletion protection is enabled for RDS database instances."
This should be changed to adapt for clusters instead of instances.

2023-09-05 01:23 UTC, simar7 approved these changes

2023-09-05 01:42 UTC, merged