feat: add support for AWS VPN `client_login_banner_options`
aquasecurity/defsec pull request #1513
Opened 2024-01-04 11:56 UTC by gantta

in support of https://github.com/aquasecurity/trivy/issues/5863, adding functionality to support the handling of the Terraform resource `aws_ec2_client_vpn_endpoint` and checks for missing `client_login_banner_options` argument.

2024-01-04 11:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/defsec?pullRequest=1513) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/defsec?pullRequest=1513) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/defsec?pullRequest=1513) it.</sub>

2024-01-14 21:36 UTC, simar7 requested changes
thanks for the PR, could you resolve the merge conflicts?

2024-02-14 15:25 UTC, gantta commented
similar to https://github.com/aquasecurity/defsec/pull/1514#issuecomment-1931243513, waiting for project refactor to be complete until we move forward with implementing this PR.

2024-03-19 14:16 UTC, gantta commented
moving changes to trivvy repo

2024-04-19 01:19 UTC, closed without merging