fix(plan): update scanning to cover more areas
aquasecurity/defsec pull request #525
Opened 2022-04-21 20:44 UTC by owenrumney

Signed-off-by: Owen Rumney <owen.rumney@aquasec.com>

2022-04-21 20:47 UTC, liamg requested changes
Couple of small comments, otherwise AOK

2022-04-21 20:47 UTC, liamg commented on pkg/scanners/terraformplan/scanner.go
> +		panic(err)
```suggestion
		return nil, err
```

2022-04-21 20:47 UTC, liamg commented on pkg/scanners/terraformplan/scanner.go
> +	fmt.Printf("Content: %s\n", string(content))
I think this is debug?

2022-04-22 05:59 UTC, owenrumney commented on pkg/scanners/terraformplan/scanner.go
> +	fmt.Printf("Content: %s\n", string(content))
yeah, my bad. Removed

2022-04-22 08:08 UTC, liamg approved these changes

2022-04-22 08:08 UTC, merged