feat: add risky role expose secrets
aquasecurity/defsec pull request #657
Opened 2022-06-05 17:01 UTC by chen-keinan

Signed-off-by: chenk <hen.keinan@gmail.com>
add risky role checks which expose secrets

2022-06-13 18:01 UTC, liamg requested changes

2022-06-13 18:53 UTC, chen-keinan commented on internal/rules/rbac/allowing_create_role_binding_and_associate_privileged_clusterrole.rego
> +	res := result.new(msg, input)
In this case, the problem when the above combination of both rules are met , so , should I return both ?

2022-06-14 08:15 UTC, liamg commented on internal/rules/rbac/allowing_create_role_binding_and_associate_privileged_clusterrole.rego
> +	res := result.new(msg, input)
I think something like this should solve the problem - the `i < j` stops the duplicate result being reported:
```rego
allowing_create_role_binding_and_associate_cluster_role[ruleA] {
	input.kind == readKinds[_]
	some i, j
	ruleA := input.rules[i]
	ruleB := input.rules[j]
	i < j
	ruleA.apiGroups[_] == "rbac.authorization.k8s.io"
	ruleA.resources[_] == "rolebindings"
	ruleA.verbs[_] == "create"
	ruleA.apiGroups[_] == "rbac.authorization.k8s.io"
	ruleB.resources[_] == ["clusterroles", "roles"][_]
	ruleB.verbs[_] == "bind"
	ruleB.resourceNames[_] == "*"
	ruleB.apiGroups[_] == "rbac.authorization.k8s.io"
}

deny[res] {
	badRule := allowing_create_role_binding_and_associate_cluster_role[_]
	msg := "Role permits creation of role binding and association with privileged role"
	res := result.new(msg, badRule)
}
```

2022-06-14 08:16 UTC, liamg commented on internal/rules/rbac/allowing_create_role_binding_and_associate_privileged_clusterrole.rego
> +	res := result.new(msg, input)
We currently only support highlighting a single map, so passing one of the two offending rules should be enough to point the user in the right direction.

2022-06-14 08:17 UTC, liamg requested changes

2022-06-14 08:17 UTC, liamg commented on internal/rules/rbac/allowing_create_role_binding_and_associate_privileged_clusterrole_test.rego
> +	count(r) > 0
I think we should use `count(r) == 1` in these tests, as we want to make sure duplicates aren't reported to the user.

2022-06-14 08:48 UTC, liamg approved these changes
LGTM :rocket:

2022-06-14 08:56 UTC, merged