feat: Add json and markdown format to --run-statistics
aquasecurity/defsec pull request #706
Opened 2022-06-23 19:12 UTC by amandahla

Proposal: add formats json and markdown to statistics output

Why: https://github.com/aquasecurity/tfsec/issues/1790

2022-06-23 19:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/defsec?pullRequest=706) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/defsec?pullRequest=706) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/defsec?pullRequest=706) it.</sub>

2022-06-23 19:31 UTC, liamg requested changes
Thanks @amandahla this is great - I've added one minor comment then we're good to merge :+1:

2022-06-23 19:31 UTC, liamg commented on pkg/scanners/terraform/executor/statistics.go
> +		fmt.Println(string(val))
We have a writer to send the output to here, i.e.
```suggestion
		_, _ = fmt.Fprintln(w, string(val))
```

2022-07-01 10:41 UTC, liamg approved these changes

2022-07-01 10:42 UTC, liamg commented
I've updated the branch with the minor change, hope this is ok :)

2022-07-01 10:56 UTC, merged

2022-07-27 13:16 UTC, amandahla commented
> I've updated the branch with the minor change, hope this is ok :)

Thanks @liamg , sorry for the delay!